name: FactionsCore
version: ${pom.version}
main: me.burnet.fcore.FactionCore
author: BurnetPv
softdepend:
  - Factions
  - HolographicDisplays
  - WorldGuard
  - WorldEdit
  - Vault
  - Essentials
commands:
  stackpots:
    description: Base command for stacking potions
  saberwand:
    aliases:
      - wand
      - wands
    description: Base command for giving wands
  slowchat:
    description: base command for slowchat
  giveall:
    description: give all players on the server an item your holding
  mutechat:
    description: base command for mutechat
  sabercore:
    description: base command for core
  playerinfo:
    description: base command for player info
  shockwave:
    description: base command for shockwaves
  chunkbuster:
    aliases:
      - cb
    description: base command for chunkbusters
  harvesterhoe:
    aliases:
      - hh
    description: base command for harvester hoes
  ping:
    description: base command for ping
  nv:
    description: base command nightvision
  setslots:
    description: base command to set the number of slots in the server.properties
  jellylegs:
    aliases:
      - jl
    description: base command for jellylegs
  lff:
    description: base command for people lff
  anvil:
    description: base command for opening anvil
  recycle:
    description: base command for recycling bottles
permissions:
  sabercore.giveall:
    description: Allows players to execute /giveall
  sabercore.staff:
    description: Allows players to use general staff commands in sabercore
  sabercore.reload:
    description: Allows access to reload FactionCore
  sabercore.disabledcommands.bypass:
    description: Allows players to execute commands that are in the disabled commands list
  sabercore.spawnermine.bypass:
    description: Allows players to bypass the enemy near spawner mine protection
  sabercore.chunkbusters.give:
    description: Allows access to give chunkbusters to players
  sabercore.harvesterhoe.give:
    description: Allows access to give harvester hoes to players
  sabercore.potstack:
    description: Allows access to /stackpots
  sabercore.anvil:
    description: Allows access to /anvil
  sabercore.jellylegs:
    description: Allows access to /jellylegs
  sabercore.lff:
    description: Allows access to /lff
  sabercore.lff.bypass:
    description: Bypasses cooldown for /lff command
  sabercore.nightvision:
    description: Allows access to /nv
  sabercore.recycle:
    description: Allows access to /recycle